# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f69dd4b67894111dccac5bdcde94f36620b2255ed708a33d889715ab9b693ce0c11eadd59d6af3d2e7eb8c0bf33700323bcdae03048e9dae35f2cfc63ce6665

test:
  secret_key_base: b3815d80a721273e94fb6e3152ef78790c5d8a7fe06bf3210cdfe80bc9b3fd08c987c96dc90f550e223732a03a5043dfdff9b7626b656ae70bd00741bc2b8da4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
